defmodule Mix.Tasks.Kaoiro.Env do
  @shortdoc "server/.env を対話生成する"

  @moduledoc """
  Interactive wizard that writes `server/.env` (issue #144, spec
  `docs/specs/setup-wizards.md`).

      mix kaoiro.env [--path .env]

  `.env` is what `docker compose` reads via `env_file:`; for a bare
  `mix phx.server` run, source it first (`set -a && . ./.env && set +a`).

  Scope notes:

    * The DETS path variables are NOT asked. The bundled
      `docker-compose.yaml` already sets them, and they only matter outside
      compose — the generated file carries them as commented hints, and the
      deployment runbook (issue #142) is the manual source of truth.
    * The runner-side counterpart is the runner's own wizard
      (`deploy/kaoiro-runner-setup.sh`). The two do not exchange tokens; this
      task prints what to paste where.
  """

  use Mix.Task

  @default_path ".env"

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [path: :string])
    path = Keyword.get(opts, :path, @default_path)

    Mix.shell().info("kaoiro server env setup\n")

    answers = %{
      secret_key_base: ask_secret(),
      phx_host: ask_required("Public hostname (PHX_HOST)", "localhost"),
      port: ask_optional("HTTP port (PORT, blank = 4000)"),
      bind_ip: ask_optional("Bind IP (KAOIRO_BIND_IP, blank = all interfaces)"),
      client_tokens: ask_client_tokens(),
      wrapper_tokens: ask_pair_tokens("wrapper", "agent_id"),
      runner_tokens: ask_pair_tokens("runner", "host_id"),
      persona_dir: ask_optional("Persona overlay dir (KAOIRO_PERSONA_DIR)")
    }

    write(path, render(answers))
  end

  # -- generation ------------------------------------------------------------

  @doc """
  32-byte hex token — the same shape as the spec's `openssl rand -hex 32`,
  without depending on the openssl binary.
  """
  def generate_token do
    32 |> :crypto.strong_rand_bytes() |> Base.encode16(case: :lower)
  end

  @doc """
  64-character base64 secret, generated exactly like `mix phx.gen.secret`
  (64 random bytes, base64, truncated to 64 chars). A 32-byte hex token is
  too short for `SECRET_KEY_BASE`.
  """
  def generate_secret do
    64 |> :crypto.strong_rand_bytes() |> Base.encode64() |> binary_part(0, 64)
  end

  @doc """
  Renders the `.env` body. Every value the wizard did not collect is emitted
  as a commented hint rather than an empty assignment, so the file stays a
  valid `env_file` and an unset-vs-blank mistake cannot creep in.
  """
  def render(answers) do
    [
      "# Generated by `mix kaoiro.env` (issue #144).",
      "# Read by docker compose via env_file:. For `mix phx.server`, source",
      "# it first: set -a && . ./.env && set +a",
      "",
      "SECRET_KEY_BASE=#{answers.secret_key_base}",
      "PHX_HOST=#{answers.phx_host}",
      optional("PORT", answers[:port], "default 4000"),
      optional(
        "KAOIRO_BIND_IP",
        answers[:bind_ip],
        ":prod only; unset = all interfaces (issue #139)"
      ),
      "",
      "# Socket auth (ADR-0011). Unset behaves differently per socket:",
      "#   CLIENT unset  -> dashboard connections are REJECTED (fail-closed)",
      "#   WRAPPER/RUNNER unset -> auth disabled in dev; prod rejects",
      "#   (issue #138). Set all three for anything network-reachable.",
      token_line("KAOIRO_CLIENT_TOKENS", answers.client_tokens),
      token_line("KAOIRO_WRAPPER_TOKENS", answers.wrapper_tokens),
      token_line("KAOIRO_RUNNER_TOKENS", answers.runner_tokens),
      "",
      optional("KAOIRO_PERSONA_DIR", answers[:persona_dir], "container path"),
      "",
      "# Restart-surviving state paths. docker-compose.yaml already sets",
      "# these; only needed when running outside compose. See the deployment",
      "# runbook (issue #142) for the full list and their meaning.",
      "#KAOIRO_SESSION_POINTERS_PATH=/var/lib/kaoiro/session_pointers.dets",
      "#KAOIRO_AGENT_DIRECTORY_PATH=/var/lib/kaoiro/agent_directory.dets",
      "#KAOIRO_PERMISSION_MODES_PATH=/var/lib/kaoiro/permission_modes.dets",
      "#KAOIRO_INTER_AGENT_HISTORY_PATH=/var/lib/kaoiro/inter_agent_history.dets",
      "#KAOIRO_CLEAR_WATERMARKS_PATH=/var/lib/kaoiro/clear_watermarks.dets",
      "#KAOIRO_SESSION_STARTS_PATH=/var/lib/kaoiro/session_starts.dets",
      "#KAOIRO_INGRESS_ORDER_PATH=/var/lib/kaoiro/ingress_order.dets",
      "#KAOIRO_TOKEN_DENYLIST_PATH=/var/lib/kaoiro/token_denylist.dets"
    ]
    |> Enum.join("\n")
    |> Kernel.<>("\n")
  end

  defp optional(name, value, hint) when value in [nil, ""] do
    "##{name}=  # #{hint}"
  end

  defp optional(name, value, _hint), do: "#{name}=#{value}"

  defp token_line(name, []), do: "##{name}="
  defp token_line(name, entries), do: "#{name}=#{Enum.join(entries, ",")}"

  # -- prompts ---------------------------------------------------------------

  defp ask_secret do
    if confirm("Generate SECRET_KEY_BASE automatically?") do
      secret = generate_secret()
      Mix.shell().info("  generated (64 chars)")
      secret
    else
      ask_required("SECRET_KEY_BASE (64+ chars)", nil)
    end
  end

  defp ask_required(label, default) do
    suffix = if default in [nil, ""], do: "", else: " [#{default}]"

    case prompt("#{label}#{suffix}") do
      "" when default in [nil, ""] ->
        Mix.shell().error("  required")
        ask_required(label, default)

      "" ->
        default

      value ->
        value
    end
  end

  defp ask_optional(label), do: prompt(label)

  # `token:role` entries. Roles are a closed set server-side, so only those
  # two are offered.
  defp ask_client_tokens do
    collect("client", fn index ->
      token = ask_token("client ##{index}")

      role =
        if confirm("  operator? (no = viewer)"),
          do: "operator",
          else: "viewer"

      "#{token}:#{role}"
    end)
  end

  # `<id>:token` entries — note the order is the reverse of client tokens.
  defp ask_pair_tokens(kind, id_label) do
    collect(kind, fn index ->
      id = ask_required("  #{kind} ##{index} #{id_label}", nil)
      "#{id}:#{ask_token("#{kind} ##{index}")}"
    end)
  end

  defp collect(kind, build) do
    if confirm("Add #{kind} tokens?") do
      collect_loop(kind, build, 1, [])
    else
      []
    end
  end

  defp collect_loop(kind, build, index, acc) do
    entry = build.(index)
    acc = acc ++ [entry]

    if confirm("Add another #{kind} token?") do
      collect_loop(kind, build, index + 1, acc)
    else
      acc
    end
  end

  defp ask_token(label) do
    if confirm("  generate the #{label} token?") do
      token = generate_token()
      Mix.shell().info("    #{token}")
      token
    else
      ask_required("  #{label} token", nil)
    end
  end

  # Mix.shell().prompt returns :eof on a closed stdin; looping on it would
  # spin forever, so treat it as an abort.
  defp prompt(label) do
    case Mix.shell().prompt("#{label}: ") do
      :eof -> Mix.raise("kaoiro.env: aborted (stdin closed)")
      value -> String.trim(value)
    end
  end

  # Not Mix.shell().yes?/1: that answers "no" on EOF, so a closed stdin would
  # look like a deliberate decline — and at the final overwrite prompt it would
  # exit 0 having written nothing. Routing through prompt/1 makes EOF abort the
  # same way it does for free-text answers.
  defp confirm(question, default \\ true) do
    hint = if default, do: "[Y/n]", else: "[y/N]"

    case String.downcase(prompt("#{question} #{hint}")) do
      "" -> default
      answer -> answer in ["y", "yes"]
    end
  end

  # -- output ----------------------------------------------------------------

  defp write(path, body) do
    # Default to NO here: overwriting a live .env destroys working tokens.
    if File.exists?(path) and
         not confirm("#{path} exists — overwrite?", false) do
      Mix.shell().info("\nKept #{path}; nothing written.")
    else
      File.write!(path, body)
      Mix.shell().info("\nWrote #{path}\n")

      Mix.shell().info("""
      Next:
        1. Review #{path} (tokens are in plain text — keep it out of git).
        2. Start the stack: docker compose up -d --build
        3. On each agent host, run the runner wizard
           (deploy/kaoiro-runner-setup.sh) and pair its token with the
           KAOIRO_RUNNER_TOKENS entry above.
      Deployment details live in the runbook (issue #142).
      """)
    end
  end
end
