defmodule Mix.Tasks.Kaoiro.Env do
  @shortdoc "server/.env を対話生成する"

  @moduledoc """
  Interactive wizard that writes `server/.env` (issue #144, spec
  `docs/specs/setup-wizards.md`).

      mix kaoiro.env [--path .env]

  `.env` is what `docker compose` reads via `env_file:`; for a bare
  `mix phx.server` run, source it first (`set -a && . ./.env && set +a`).

  Scope notes:

    * The DETS path variables are NOT asked. The bundled
      `docker-compose.yaml` already sets them, and they only matter outside
      compose — the generated file carries them as commented hints, and the
      deployment runbook (issue #142) is the manual source of truth.
    * The runner-side counterpart is the runner's own wizard
      (`deploy/kaoiro-runner-setup.sh`). The two do not exchange tokens; this
      task prints what to paste where.
  """

  use Mix.Task

  @default_path ".env"

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [path: :string])
    path = Keyword.get(opts, :path, @default_path)

    Mix.shell().info("kaoiro server env setup\n")

    answers = %{
      secret_key_base: ask_secret(),
      phx_host: ask_required("Public hostname (PHX_HOST)", "localhost"),
      port: ask_optional("HTTP port (PORT, blank = 4000)"),
      bind_ip: ask_optional("Bind IP (KAOIRO_BIND_IP, blank = all interfaces)"),
      client_tokens: ask_client_tokens(),
      wrapper_tokens: ask_pair_tokens("wrapper", "agent_id"),
      runner_tokens: ask_pair_tokens("runner", "host_id"),
      persona_dir: ask_optional("Persona overlay dir (KAOIRO_PERSONA_DIR)"),
      oauth: ask_oauth()
    }

    write(path, render(answers), answers.oauth)
  end

  # -- generation ------------------------------------------------------------

  @doc """
  32-byte hex token — the same shape as the spec's `openssl rand -hex 32`,
  without depending on the openssl binary.
  """
  def generate_token do
    32 |> :crypto.strong_rand_bytes() |> Base.encode16(case: :lower)
  end

  @doc """
  64-character base64 secret, generated exactly like `mix phx.gen.secret`
  (64 random bytes, base64, truncated to 64 chars). A 32-byte hex token is
  too short for `SECRET_KEY_BASE`.
  """
  def generate_secret do
    64 |> :crypto.strong_rand_bytes() |> Base.encode64() |> binary_part(0, 64)
  end

  @doc """
  Renders the `.env` body. Every value the wizard did not collect is emitted
  as a commented hint rather than an empty assignment, so the file stays a
  valid `env_file` and an unset-vs-blank mistake cannot creep in.
  """
  def render(answers) do
    [
      "# Generated by `mix kaoiro.env` (issue #144).",
      "# Read by docker compose via env_file:. For `mix phx.server`, source",
      "# it first: set -a && . ./.env && set +a",
      "",
      "SECRET_KEY_BASE=#{answers.secret_key_base}",
      "PHX_HOST=#{answers.phx_host}",
      optional("PORT", answers[:port], "default 4000"),
      optional(
        "KAOIRO_BIND_IP",
        answers[:bind_ip],
        ":prod only; unset = all interfaces (issue #139)"
      ),
      "",
      "# Socket auth (ADR-0011). Unset behaves differently per socket:",
      "#   CLIENT token unset -> dashboard token authentication is REJECTED (fail-closed)",
      "#   WRAPPER/RUNNER unset -> auth disabled in dev; prod rejects",
      "#   (issue #138). Set all three for anything network-reachable.",
      oauth_auth_note(answers[:oauth]),
      token_line("KAOIRO_CLIENT_TOKENS", answers.client_tokens),
      token_line("KAOIRO_WRAPPER_TOKENS", answers.wrapper_tokens),
      token_line("KAOIRO_RUNNER_TOKENS", answers.runner_tokens),
      oauth_env_lines(answers[:oauth]),
      "",
      optional("KAOIRO_PERSONA_DIR", answers[:persona_dir], "container path"),
      "",
      "# Persona extraction cache root (ADR-0046) and common-footer dir",
      "# (ADR-0045). Not asked: docker-compose.yaml already sets the cache",
      "# root, and footers are opt-in. Set the footer dir only if you want",
      "# to edit system-footer.md / user-footer.md without a rebuild; mount",
      "# it read-only and keep both files out of git.",
      "#KAOIRO_PERSONA_CACHE_DIR=/var/lib/kaoiro/persona-cache",
      "#KAOIRO_FOOTER_DIR=/etc/kaoiro/footers",
      "",
      "# Restart-surviving state paths. docker-compose.yaml already sets",
      "# these; only needed when running outside compose. See the deployment",
      "# runbook (issue #142) for the full list and their meaning.",
      "#KAOIRO_SESSION_POINTERS_PATH=/var/lib/kaoiro/session_pointers.dets",
      "#KAOIRO_AGENT_DIRECTORY_PATH=/var/lib/kaoiro/agent_directory.dets",
      "#KAOIRO_PERMISSION_MODES_PATH=/var/lib/kaoiro/permission_modes.dets",
      "#KAOIRO_CLEAR_WATERMARKS_PATH=/var/lib/kaoiro/clear_watermarks.dets",
      "#KAOIRO_SESSION_STARTS_PATH=/var/lib/kaoiro/session_starts.dets",
      "#KAOIRO_INGRESS_ORDER_PATH=/var/lib/kaoiro/ingress_order.dets",
      "#KAOIRO_TOKEN_DENYLIST_PATH=/var/lib/kaoiro/token_denylist.dets"
    ]
    |> List.flatten()
    |> Enum.join("\n")
    |> Kernel.<>("\n")
  end

  @doc """
  Renders the editable OAuth allow-list mounted into the compose container.
  Entries deliberately remain plain `provider:identifier[:role]` lines so
  removing an account is a small, reviewable file edit (ADR-0042).
  """
  def render_allowlist(entries) do
    [
      "# Kaoiro OAuth allow-list (ADR-0042).",
      "# One entry per line: provider:identifier[:role]",
      "# provider: google | github | nextcloud",
      "# identifier: google=email (case-insensitive); github=login; nextcloud=user id",
      "# role: viewer | operator (optional; defaults to viewer)",
      "# Blank lines and lines starting with # are ignored.",
      "",
      entries
    ]
    |> List.flatten()
    |> Enum.join("\n")
    |> Kernel.<>("\n")
  end

  defp optional(name, value, hint) when value in [nil, ""] do
    "##{name}=  # #{hint}"
  end

  defp optional(name, value, _hint), do: "#{name}=#{value}"

  defp token_line(name, []), do: "##{name}="
  defp token_line(name, entries), do: "#{name}=#{Enum.join(entries, ",")}"

  defp oauth_auth_note(%{providers: [_ | _]}) do
    "# OAuth login is enabled; access follows the allow-list (ADR-0042)."
  end

  defp oauth_auth_note(_), do: []

  defp oauth_env_lines(%{providers: [_ | _] = providers}) do
    [
      "",
      "# Dashboard OAuth login (ADR-0042).",
      Enum.flat_map(providers, &provider_env_lines/1),
      "KAOIRO_OAUTH_ALLOWLIST_PATH=/etc/kaoiro/oauth-allowlist.txt"
    ]
  end

  defp oauth_env_lines(_), do: []

  defp provider_env_lines(%{provider: "nextcloud"} = provider) do
    [
      "KAOIRO_OAUTH_NEXTCLOUD_CLIENT_ID=#{provider.client_id}",
      "KAOIRO_OAUTH_NEXTCLOUD_CLIENT_SECRET=#{provider.client_secret}",
      "KAOIRO_OAUTH_NEXTCLOUD_BASE_URL=#{provider.base_url}"
    ]
  end

  defp provider_env_lines(%{provider: provider} = config) do
    prefix = provider |> String.upcase() |> then(&"KAOIRO_OAUTH_#{&1}")

    [
      "#{prefix}_CLIENT_ID=#{config.client_id}",
      "#{prefix}_CLIENT_SECRET=#{config.client_secret}"
    ]
  end

  # -- prompts ---------------------------------------------------------------

  defp ask_secret do
    if confirm("Generate SECRET_KEY_BASE automatically?") do
      secret = generate_secret()
      Mix.shell().info("  generated (64 chars)")
      secret
    else
      ask_required("SECRET_KEY_BASE (64+ chars)", nil)
    end
  end

  defp ask_required(label, default) do
    suffix = if default in [nil, ""], do: "", else: " [#{default}]"

    case prompt("#{label}#{suffix}") do
      "" when default in [nil, ""] ->
        Mix.shell().error("  required")
        ask_required(label, default)

      "" ->
        default

      value ->
        value
    end
  end

  defp ask_optional(label), do: prompt(label)

  # OAuth credentials belong to provider consoles and are intentionally never
  # generated here. In particular, do not print them back as a confirmation:
  # the generated .env is the only place this task writes them.
  defp ask_oauth do
    if confirm("Configure OAuth login?", false) do
      providers =
        [
          ask_oauth_provider("google"),
          ask_oauth_provider("github"),
          ask_oauth_provider("nextcloud")
        ]
        |> Enum.reject(&is_nil/1)

      case providers do
        [] ->
          Mix.shell().info("  no provider enabled; OAuth settings will not be written")
          nil

        _ ->
          %{providers: providers, allowlist_entries: ask_allowlist_entries()}
      end
    end
  end

  defp ask_oauth_provider(provider) do
    if confirm("Enable #{provider} OAuth login?", false) do
      config = %{
        provider: provider,
        client_id: ask_required("  #{provider} client ID", nil),
        client_secret: ask_required("  #{provider} client secret", nil)
      }

      if provider == "nextcloud" do
        Map.put(config, :base_url, ask_required("  nextcloud base URL", nil))
      else
        config
      end
    end
  end

  defp ask_allowlist_entries do
    Mix.shell().info(
      "  Add at least one OAuth allow-list entry. An empty or missing allow-list " <>
        "rejects every OAuth login (fail-closed)."
    )

    collect_allowlist_entries(1, [])
  end

  defp collect_allowlist_entries(index, entries) do
    entry = ask_allowlist_entry(index)
    entries = entries ++ [entry]

    if confirm("Add another OAuth allow-list entry?", false) do
      collect_allowlist_entries(index + 1, entries)
    else
      entries
    end
  end

  defp ask_allowlist_entry(index) do
    value =
      ask_required(
        "  OAuth allow-list entry ##{index} (provider:identifier[:role]; role defaults to viewer)",
        nil
      )

    case normalize_allowlist_entry(value) do
      {:ok, entry} ->
        entry

      :error ->
        Mix.shell().error("  expected provider:identifier[:role] (role: viewer or operator)")
        ask_allowlist_entry(index)
    end
  end

  defp normalize_allowlist_entry(value) do
    case value |> String.split(":") |> Enum.map(&String.trim/1) do
      [provider, identifier]
      when provider in ["google", "github", "nextcloud"] and identifier != "" ->
        {:ok, "#{provider}:#{identifier}"}

      [provider, identifier, role]
      when provider in ["google", "github", "nextcloud"] and identifier != "" and
             role in ["viewer", "operator"] ->
        {:ok, "#{provider}:#{identifier}:#{role}"}

      _ ->
        :error
    end
  end

  # `token:role` entries. Roles are a closed set server-side, so only those
  # two are offered.
  defp ask_client_tokens do
    collect("client", fn index ->
      token = ask_token("client ##{index}")

      role =
        if confirm("  operator? (no = viewer)"),
          do: "operator",
          else: "viewer"

      "#{token}:#{role}"
    end)
  end

  # `<id>:token` entries — note the order is the reverse of client tokens.
  defp ask_pair_tokens(kind, id_label) do
    collect(kind, fn index ->
      id = ask_required("  #{kind} ##{index} #{id_label}", nil)
      "#{id}:#{ask_token("#{kind} ##{index}")}"
    end)
  end

  defp collect(kind, build) do
    if confirm("Add #{kind} tokens?") do
      collect_loop(kind, build, 1, [])
    else
      []
    end
  end

  defp collect_loop(kind, build, index, acc) do
    entry = build.(index)
    acc = acc ++ [entry]

    if confirm("Add another #{kind} token?") do
      collect_loop(kind, build, index + 1, acc)
    else
      acc
    end
  end

  defp ask_token(label) do
    if confirm("  generate the #{label} token?") do
      token = generate_token()
      Mix.shell().info("    #{token}")
      token
    else
      ask_required("  #{label} token", nil)
    end
  end

  # Mix.shell().prompt returns :eof on a closed stdin; looping on it would
  # spin forever, so treat it as an abort.
  defp prompt(label) do
    case Mix.shell().prompt("#{label}: ") do
      :eof -> Mix.raise("kaoiro.env: aborted (stdin closed)")
      value -> String.trim(value)
    end
  end

  # Not Mix.shell().yes?/1: that answers "no" on EOF, so a closed stdin would
  # look like a deliberate decline — and at the final overwrite prompt it would
  # exit 0 having written nothing. Routing through prompt/1 makes EOF abort the
  # same way it does for free-text answers.
  defp confirm(question, default \\ true) do
    hint = if default, do: "[Y/n]", else: "[y/N]"

    case String.downcase(prompt("#{question} #{hint}")) do
      "" -> default
      answer -> answer in ["y", "yes"]
    end
  end

  # -- output ----------------------------------------------------------------

  defp write(path, body, oauth) do
    # Default to NO here: overwriting a live .env destroys working tokens.
    if File.exists?(path) and
         not confirm("#{path} exists — overwrite?", false) do
      Mix.shell().info("\nKept #{path}; nothing written.")
    else
      File.write!(path, body)
      File.chmod!(path, 0o600)
      Mix.shell().info("\nWrote #{path}\n")

      write_allowlist(path, oauth)
      print_next_steps(path, oauth)
    end
  end

  defp write_allowlist(_path, %{providers: []}), do: :ok
  defp write_allowlist(_path, nil), do: :ok

  defp write_allowlist(env_path, %{allowlist_entries: entries}) do
    path = allowlist_path(env_path)

    if File.exists?(path) and not confirm("#{path} exists — overwrite?", false) do
      Mix.shell().info("Kept #{path}; existing OAuth allow-list unchanged.\n")
    else
      File.write!(path, render_allowlist(entries))
      File.chmod!(path, 0o600)
      Mix.shell().info("Wrote #{path}\n")
    end
  end

  defp allowlist_path(env_path), do: Path.join(Path.dirname(env_path), "oauth-allowlist.txt")

  defp print_next_steps(path, oauth = %{providers: [_ | _]}) do
    allowlist_path = allowlist_path(path)
    mount_source = compose_mount_source(allowlist_path)
    {google_steps, start_step, runner_step} = google_next_steps(oauth)

    steps =
      [
        "1. Review #{path} (tokens and OAuth secrets are in plain text — keep it out of git).",
        "2. Keep #{allowlist_path} out of git, then add this read-only mount under\n" <>
          "     docker-compose.yaml's service `volumes:`:\n" <>
          "       - #{mount_source}:/etc/kaoiro/oauth-allowlist.txt:ro",
        "3. Register each provider's redirect URI in its console; see\n" <>
          "     docs/specs/deployment.md section 1.6."
      ] ++
        google_steps ++
        [
          "#{start_step}. Start the stack: docker compose up -d --build",
          "#{runner_step}. On each agent host, run the runner wizard\n" <>
            "     (deploy/kaoiro-runner-setup.sh) and pair its token with the\n" <>
            "     KAOIRO_RUNNER_TOKENS entry above."
        ]

    Mix.shell().info("""
    Next:
      #{Enum.join(steps, "\n  ")}
    Deployment details live in the runbook (issue #142).
    """)
  end

  defp print_next_steps(path, _oauth) do
    Mix.shell().info("""
    Next:
      1. Review #{path} (tokens are in plain text — keep it out of git).
      2. Start the stack: docker compose up -d --build
      3. On each agent host, run the runner wizard
         (deploy/kaoiro-runner-setup.sh) and pair its token with the
         KAOIRO_RUNNER_TOKENS entry above.
    Deployment details live in the runbook (issue #142).
    """)
  end

  defp compose_mount_source("./" <> _rest = path), do: path

  defp compose_mount_source(path) do
    if Path.type(path) == :absolute, do: path, else: "./#{path}"
  end

  defp google_next_steps(%{providers: providers}) do
    if Enum.any?(providers, &(&1.provider == "google")) do
      {[
         "4. Google OAuth cannot be used on a plain-HTTP deployment (localhost is the exception)."
       ], 5, 6}
    else
      {[], 4, 5}
    end
  end
end
