// #184 M4: input-latency bench. Boots a throwaway Vite dev server serving
// bench/harness.html, drives it with Playwright/chromium, and measures the
// gap between a composer keystroke (`input` event) and the next painted
// frame — the #184 hypothesis (layout/style recalc over the huge transcript
// DOM) shows up as a gap here. Runs the SAME measurement against two
// variants of AgentDetail: "before" (a pinned pre-#184 baseline, materialised
// on the fly below — see writeBeforeSnapshot) and "after" (the current
// src/lib/AgentDetail.svelte). Re-run any time with:
//
//   PATH="$HOME/.asdf/shims:$PATH" node bench/runBench.mjs [count] [keystrokes] [mode]
//
// Requires `pnpm exec playwright install chromium` once per machine (see
// README.md in this directory for the full writeup and setup).
import { chromium } from "@playwright/test";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

// ふじ round-2 must-fix S2: a permanent AgentDetail.before.svelte committed
// under src/lib/ reads as shipped code and drifts silently from its cited
// baseline. Materialise it on the fly instead, pinned to the commit just
// before the #184 window landed, and delete it when the bench finishes
// (see .gitignore — it must never be a tracked file).
const BASELINE_SHA = "37e89a3640a02fbd4524a0f36630d8e8e0db0c38";
const BEFORE_SNAPSHOT_PATH = path.join(
  root,
  "src/lib/.AgentDetail.before.bench.svelte",
);

function writeBeforeSnapshot() {
  const content = execFileSync(
    "git",
    ["show", `${BASELINE_SHA}:dashboard/src/lib/AgentDetail.svelte`],
    { cwd: root, encoding: "utf8" },
  );
  const header = `<!--\n  #184 M4 bench fixture — generated by runBench.mjs from baseline\n  ${BASELINE_SHA} (git show <SHA>:dashboard/src/lib/AgentDetail.svelte),\n  the commit immediately before the #184 render-window fix. Temporary:\n  deleted when the bench run finishes. Do not edit or commit (gitignored).\n-->\n`;
  fs.writeFileSync(BEFORE_SNAPSHOT_PATH, header + content);
}

function removeBeforeSnapshot() {
  fs.rmSync(BEFORE_SNAPSHOT_PATH, { force: true });
}

async function withServer(fn) {
  const server = await createServer({
    root,
    configFile: path.join(root, "vite.config.ts"),
    server: { port: 0 },
    logLevel: "error",
  });
  await server.listen();
  const address = server.httpServer?.address();
  const port = typeof address === "object" && address ? address.port : address;
  try {
    return await fn(`http://localhost:${port}`);
  } finally {
    await server.close();
  }
}

async function measure(page, baseUrl, variant, count, keystrokes, mode) {
  await page.goto(`${baseUrl}/bench/harness.html?variant=${variant}&count=${count}`, {
    waitUntil: "load",
  });
  await page.waitForSelector(".log", { timeout: 120000 });
  // Let the initial mount (+ mermaid pass) settle before measuring so the
  // first keystroke isn't charged for one-time mount cost.
  await page.waitForTimeout(1500);
  await page.evaluate(() => window.__armLatencyProbe());
  const textarea = page.locator("textarea").first();
  await textarea.click();
  for (let i = 0; i < keystrokes; i++) {
    if (mode === "slash") {
      // Round-1 code review narrowed the #184 hypothesis: a plain keystroke
      // does not itself force a reflow of the huge transcript (Svelte 5
      // fine-grained reactivity only touches the `instruction` $state).
      // Opening the slash-command menu DOES: it inserts a <ul> sibling
      // in-flow inside the same scrollable container as the transcript
      // (AgentDetail.svelte's `.log`), which is exactly where an unbounded
      // DOM should show a cost the render window is meant to remove. Each
      // cycle opens ("/") then closes (Backspace) the menu.
      await textarea.type("/", { delay: 0 });
      await page.waitForTimeout(30);
      await textarea.press("Backspace");
    } else {
      await textarea.type("a", { delay: 0 });
    }
    // Give the RAF sample time to land before the next keystroke so samples
    // don't overlap.
    await page.waitForTimeout(30);
  }
  return page.evaluate(() => window.__latencies);
}

function stats(latencies) {
  const sorted = [...latencies].sort((a, b) => a - b);
  const sum = sorted.reduce((a, b) => a + b, 0);
  const pct = (p) =>
    sorted[Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))];
  return {
    n: sorted.length,
    avgMs: Number((sum / sorted.length).toFixed(2)),
    medianMs: Number(pct(50).toFixed(2)),
    p95Ms: Number(pct(95).toFixed(2)),
    maxMs: Number(pct(100).toFixed(2)),
  };
}

const COUNT = Number(process.argv[2] ?? "1000");
const KEYSTROKES = Number(process.argv[3] ?? "30");
const MODE = process.argv[4] ?? "slash"; // "slash" | "plain"

writeBeforeSnapshot();
try {
  await withServer(async (baseUrl) => {
    const browser = await chromium.launch();
    const results = {};
    for (const variant of ["before", "after"]) {
      const page = await browser.newPage();
      const latencies = await measure(page, baseUrl, variant, COUNT, KEYSTROKES, MODE);
      results[variant] = stats(latencies);
      console.log(variant, JSON.stringify(results[variant]));
      await page.close();
    }
    await browser.close();

    const outDir = path.join(__dirname, "results");
    fs.mkdirSync(outDir, { recursive: true });
    const outFile = path.join(outDir, `inputLatency-${MODE}-${COUNT}.json`);
    fs.writeFileSync(
      outFile,
      JSON.stringify({ count: COUNT, keystrokes: KEYSTROKES, mode: MODE, ...results }, null, 2),
    );
    console.log("written", outFile);
  });
} finally {
  removeBeforeSnapshot();
}
