// issue #304 M2/M3: App-level input-latency bench. Mounts the REAL
// src/App.svelte (see bench/harnessApp.ts) against bench/fakePhoenix.ts and
// drives it with Playwright, comparing "before" (1c399eae^, the commit
// immediately before candidate A -- App.svelte's latestErrorKeyByAgent
// full-transcript rescan on every `logs` replacement) against "after" (the
// current worktree). Adds Event Timing (input delay / processing /
// presentation), long tasks, DOM node count, and a Playwright trace on top
// of the #174-era rAF-only metric (kept for comparability).
//
//   PATH="$HOME/.asdf/shims:$PATH" node bench/runBenchApp.mjs \
//     [agentCount] [historyCount] [keystrokes] [tickMs] [errorAgents] [runLabel]
//
// agentCount:   total agents seeded (1 viewed + agentCount-1 background)
// historyCount: synthetic transcript length per agent
// keystrokes:   composer keystrokes typed (plain "a", one per ~30ms cycle)
// tickMs:       interval between live-log receive ticks, sent to the
//               viewed agent AND one background agent at this SAME
//               frequency each tick (candidate A's own reproduction recipe)
// errorAgents:  "all" | "none" -- whether every seeded agent's history ends
//               with an is_error result (candidate A: "error あり/なし")
// runLabel:     optional (e.g. "run1") -- appended to the output JSON/trace
//               filenames so repeated runs of the SAME scenario land in
//               separate files instead of silently overwriting each other.
import { chromium } from "@playwright/test";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

// The commit immediately before candidate A (issue #287 fuji2 round-1 M1)
// replaced a plain `$state` sticky-badge write (set once per matching live
// envelope) with `latestErrorKeyByAgent`, a `$derived.by` that rescans
// EVERY agent's WHOLE transcript backwards on every `logs` replacement.
// App.svelte is the only file this isolates -- latestReply.ts also changed
// in 1c399eae but for an unrelated error-text fallback, not this path.
const BASELINE_SHA = "1c399eae1c278bfa4892019350dc1ad4ccd7afde^";
const BEFORE_SNAPSHOT_PATH = path.join(root, "src/.App.before.bench.svelte");

function writeBeforeSnapshot() {
  const content = execFileSync(
    "git",
    ["show", `${BASELINE_SHA}:dashboard/src/App.svelte`],
    { cwd: root, encoding: "utf8" },
  );
  const header = `<!--\n  issue #304 bench fixture -- generated by runBenchApp.mjs from baseline\n  ${BASELINE_SHA} (git show <SHA>:dashboard/src/App.svelte), the commit\n  immediately before candidate A (issue #287 fuji2 M1). Temporary: deleted\n  when the bench run finishes. Do not edit or commit (gitignored).\n-->\n`;
  fs.writeFileSync(BEFORE_SNAPSHOT_PATH, header + content);
}

function removeBeforeSnapshot() {
  fs.rmSync(BEFORE_SNAPSHOT_PATH, { force: true });
}

async function withServer(fn) {
  const server = await createServer({
    root,
    configFile: path.join(__dirname, "vite.harness.config.ts"),
    server: { port: 0 },
    logLevel: "error",
  });
  await server.listen();
  const address = server.httpServer?.address();
  const port = typeof address === "object" && address ? address.port : address;
  try {
    return await fn(`http://localhost:${port}`);
  } finally {
    await server.close();
  }
}

function armProbes(page) {
  return page.evaluate(() => {
    window.__bench.armLatencyProbe();
    window.__eventTimings = [];
    // `buffered: true` deliberately OMITTED here: it would replay entries
    // from before this point (mount, seed, click-into-detail), inflating
    // these stats with one-time setup cost instead of isolating the
    // during-typing/during-receive-tick window this function arms for.
    new PerformanceObserver((list) => {
      for (const e of list.getEntries()) {
        window.__eventTimings.push({
          name: e.name,
          startTime: e.startTime,
          duration: e.duration,
          inputDelay: e.processingStart - e.startTime,
          processingTime: e.processingEnd - e.processingStart,
          presentationDelay: e.duration - (e.processingEnd - e.startTime),
        });
      }
    }).observe({ type: "event", durationThreshold: 16 });
    window.__longTasks = [];
    new PerformanceObserver((list) => {
      for (const e of list.getEntries()) {
        window.__longTasks.push({
          name: e.name,
          startTime: e.startTime,
          duration: e.duration,
          attribution: (e.attribution ?? []).map((a) => ({
            name: a.name,
            containerType: a.containerType,
          })),
        });
      }
    }).observe({ type: "longtask" });
  });
}

/** Registers a buffered 'longtask' observer as early as possible after
 *  navigation, to report one-time mount cost SEPARATELY from the
 *  during-typing/during-receive-tick window (not mixed into it).
 *  `buffered: true` retroactively replays the browser's own long-task
 *  entry buffer back to navigation start (confirmed against web.dev's
 *  Long Tasks API guidance), so arming this right after page.goto still
 *  sees mount-time tasks even though page.evaluate() only runs after the
 *  page's own scripts have already started. Kept as a separate
 *  observer/array from armProbes()'s during-typing one (window.__longTasks),
 *  so disconnecting it in mountCostSoFar() below can never affect that
 *  window's data. */
function armMountCostProbe(page) {
  return page.evaluate(() => {
    window.__mountLongTasks = [];
    window.__mountLongTaskObserver = new PerformanceObserver((list) => {
      for (const e of list.getEntries()) {
        window.__mountLongTasks.push({
          name: e.name,
          startTime: e.startTime,
          duration: e.duration,
        });
      }
    });
    window.__mountLongTaskObserver.observe({ type: "longtask", buffered: true });
  });
}

/** Reads + disconnects the probe armed by armMountCostProbe. Cannot use
 *  `performance.getEntriesByType("longtask")` here: per the Performance
 *  Timeline spec (confirmed against MDN's Performance.getEntriesByType()
 *  docs), "longtask" -- along with "event", "element",
 *  "largest-contentful-paint", "layout-shift" -- is observer-only and is
 *  never returned by getEntriesByType()/getEntries(), buffered or not;
 *  that call always returns []. */
function mountCostSoFar(page) {
  return page.evaluate(() => {
    window.__mountLongTaskObserver?.disconnect();
    return { longTasks: window.__mountLongTasks ?? [] };
  });
}

/** Types "/" into the composer and confirms `.slash-menu` (AgentDetail.
 *  svelte, #34) actually appears -- the seeded `ext.slash_commands`
 *  (measure()'s agents array) only wires the DATA the menu needs; this is
 *  the observation that it renders. Clears the composer afterward so the
 *  candidate-A keystroke loop below starts from an empty textarea, not
 *  "/" left behind. Throws (via waitForSelector) on failure -- see
 *  measure()'s call site comment for why a throw here still needs
 *  checkForFailures below to become a non-zero process exit. */
async function verifySlashMenu(page) {
  const textarea = page.locator("textarea").first();
  await textarea.click();
  await textarea.fill("/");
  await page.waitForSelector(".slash-menu", { timeout: 5000 });
  await textarea.fill("");
}

async function measure(page, baseUrl, variant, opts) {
  const {
    agentCount,
    historyCount,
    keystrokes,
    tickMs,
    errorAgents,
    traceDir,
    runLabel,
  } = opts;
  await page.goto(
    `${baseUrl}/bench/harnessApp.html?variant=${variant}&token=bench-${variant}`,
    { waitUntil: "load" },
  );
  await armMountCostProbe(page);
  await page.evaluate(() => window.__bench.waitReady());

  const agents = Array.from({ length: agentCount }, (_, i) => ({
    agentId: i === 0 ? "agent-viewed" : `agent-bg-${i}`,
    historyCount,
    withRecentError: errorAgents === "all",
    ext:
      i === 0
        ? { slash_commands: ["new", "clear", "help"] }
        : undefined,
  }));
  await page.evaluate((a) => window.__bench.seed(a), agents);
  // Let the initial mount + snapshot/history render settle before opening
  // the detail view or measuring, mirroring bench/harness.ts's 1500ms
  // settle window.
  await page.waitForTimeout(1500);

  await page
    .locator("button.open", { hasText: "agent-viewed" })
    .click();
  await page.waitForSelector(".log", { timeout: 30000 });
  await page.waitForTimeout(500);

  const mountCost = await mountCostSoFar(page);
  // This harness supplies `ext.slash_commands` so AgentDetail's slash menu
  // has the data it needs, but that alone never confirmed the menu
  // actually renders -- the exact "fixed a wiring gap but never observed
  // it working" mistake #174's own bench made once already. Placed AFTER
  // mountCostSoFar (its own long tasks must not inflate reported mount
  // cost) and BEFORE armProbes (which arms a non-buffered observer, so
  // this activity must not leak into the during-typing window either) --
  // this gap is invisible to both metric buckets. Throws (via
  // waitForSelector's timeout) on failure, which propagates out of
  // measure() to the caller's try/catch -- see scenarioFailed below for
  // why that alone is not yet a non-zero exit.
  await verifySlashMenu(page);
  await armProbes(page);

  const domCountBefore = await page.evaluate(
    () => document.querySelectorAll("*").length,
  );

  await page.context().tracing.start({ screenshots: false, snapshots: false });

  // Receive-tick generator: same frequency to the viewed agent and one
  // background agent every tick, running concurrently with the composer
  // keystrokes below (candidate A's own reproduction recipe: "閲覧agentと
  // 背景agentへの同頻度送信"). try/finally: candidate A's whole failure
  // mode is the page becoming unresponsive long enough for `textarea.type`
  // to time out below -- without this, the leaked interval keeps firing
  // page.evaluate() against an already-closed page after the catch in the
  // caller closes it, crashing the whole script instead of just failing
  // this one variant's measurement.
  let seqCounter = historyCount + 1;
  let tickHandle;
  if (agentCount > 1 && tickMs > 0) {
    tickHandle = setInterval(() => {
      const seq = seqCounter++;
      page
        .evaluate(
          ({ seq }) => {
            window.__bench.sendLog("agent-viewed", seq);
            window.__bench.sendLog("agent-bg-1", seq);
          },
          { seq },
        )
        .catch(() => {
          // Page busy/closed -- expected under the exact contention this
          // scenario is trying to provoke; the next tick (or the outer
          // clearInterval) is the recovery, not this call.
        });
    }, tickMs);
  }

  let typingError = null;
  let keystrokesCompleted = 0;
  try {
    const textarea = page.locator("textarea").first();
    await textarea.click();
    for (let i = 0; i < keystrokes; i++) {
      await textarea.type("a", { delay: 0 });
      keystrokesCompleted++;
      await page.waitForTimeout(30);
    }
  } catch (err) {
    // Candidate A's own failure mode -- a hung main thread that starves
    // even a single keystroke past this run's timeout. Keep the partial
    // trace/samples gathered up to this point rather than losing the
    // whole measurement to the exception.
    typingError = String(err?.message ?? err);
  } finally {
    if (tickHandle) clearInterval(tickHandle);
  }
  await page.waitForTimeout(200).catch(() => {});

  const tracePath = path.join(
    traceDir,
    `trace-agents${agentCount}-hist${historyCount}-tick${tickMs}-err${errorAgents}${runLabel ? `-${runLabel}` : ""}-${variant}.zip`,
  );
  await page.context().tracing.stop({ path: tracePath }).catch(() => {});

  const domCountAfter = await page
    .evaluate(() => document.querySelectorAll("*").length)
    .catch(() => null);
  // A read failure here (page died, evaluate() rejected) and a
  // legitimately empty result look IDENTICAL once caught into `[]` --
  // `readFailed` keeps them apart so scenarioFailed can gate on the
  // former without ever mistaking a genuinely empty Event Timing/Long
  // Task array (both can legitimately be empty) for a failure.
  let readFailed = false;
  const onReadFailure = () => {
    readFailed = true;
    return [];
  };
  const latencies = await page
    .evaluate(() => window.__latencies)
    .catch(onReadFailure);
  const eventTimings = await page
    .evaluate(() => window.__eventTimings)
    .catch(onReadFailure);
  const longTasks = await page
    .evaluate(() => window.__longTasks)
    .catch(onReadFailure);

  return {
    latencies,
    eventTimings,
    longTasks,
    readFailed,
    mountLongTasks: mountCost.longTasks,
    domCountBefore,
    domCountAfter,
    tracePath,
    typingError,
    keystrokesCompleted,
    keystrokesRequested: keystrokes,
  };
}

function stats(values) {
  if (values.length === 0) return { n: 0 };
  const sorted = [...values].sort((a, b) => a - b);
  const sum = sorted.reduce((a, b) => a + b, 0);
  const pct = (p) =>
    sorted[Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))];
  return {
    n: sorted.length,
    avg: Number((sum / sorted.length).toFixed(2)),
    median: Number(pct(50).toFixed(2)),
    p95: Number(pct(95).toFixed(2)),
    max: Number(pct(100).toFixed(2)),
  };
}

function summarize(raw) {
  return {
    rafLatencyMs: stats(raw.latencies),
    eventTiming: {
      inputDelayMs: stats(raw.eventTimings.map((e) => e.inputDelay)),
      processingTimeMs: stats(raw.eventTimings.map((e) => e.processingTime)),
      presentationDelayMs: stats(raw.eventTimings.map((e) => e.presentationDelay)),
      durationMs: stats(raw.eventTimings.map((e) => e.duration)),
    },
    longTasks: {
      count: raw.longTasks.length,
      totalDurationMs: Number(
        raw.longTasks.reduce((a, t) => a + t.duration, 0).toFixed(2),
      ),
      durationMs: stats(raw.longTasks.map((t) => t.duration)),
    },
    mountLongTasks: {
      count: raw.mountLongTasks.length,
      totalDurationMs: Number(
        raw.mountLongTasks.reduce((a, t) => a + t.duration, 0).toFixed(2),
      ),
    },
    domNodeCount: { before: raw.domCountBefore, after: raw.domCountAfter },
    tracePath: raw.tracePath,
    typingError: raw.typingError,
    readFailed: raw.readFailed,
    keystrokes: { completed: raw.keystrokesCompleted, requested: raw.keystrokesRequested },
  };
}

/** The main loop's own try/catch (below) records a
 *  failed variant into `results[variant].error` so ONE variant's failure
 *  does not lose the other's data -- but that alone leaves the PROCESS
 *  exiting 0 even when a variant never produced a valid measurement
 *  (harness error, slash-menu did not appear, typing never finished, or a
 *  required field came back null because the page died mid-read). This
 *  scans the finished `results` for exactly those cases; the caller sets
 *  `process.exitCode` from it, which is what actually makes the
 *  invocation non-zero (see README's own negative control: reject
 *  __bench.waitReady and confirm the exit code, not just the printed
 *  JSON -- catching a rejection is not the same as failing the process). */
function scenarioFailed(result) {
  if (!result || result.error) return true;
  if (result.typingError) return true;
  if (result.keystrokes.completed < result.keystrokes.requested) return true;
  if (result.domNodeCount.after === null) return true;
  // A read (page.evaluate) failure for latencies/eventTimings/longTasks
  // is caught into `[]` so the rest of summarize() still has arrays to
  // work with, but that also makes it indistinguishable from a
  // legitimately empty result -- `readFailed` is set by that SAME catch
  // path specifically to keep the two apart, and is a failure on its own
  // regardless of what keystrokes/rAF report.
  if (result.readFailed) return true;
  // A completed keystroke run with ZERO rAF latency samples means either
  // the probe's own wiring failed (armLatencyProbe's `input` listener
  // never fired) or its read-back failed (page died before
  // page.evaluate() could read window.__latencies) -- reject.catch(() =>
  // []) makes both of those indistinguishable from a legitimately empty
  // array, so a completed-but-zero-sample run is treated as a
  // measurement failure here rather than a valid "0 samples" result.
  // Event Timing / Long Tasks are NOT held to this: a fast run
  // genuinely can have zero events >16ms or zero long tasks, and there
  // is no analogous "this MUST have produced at least one sample"
  // guarantee for them the way there is for rAF once >=1 keystroke has
  // landed.
  if (result.keystrokes.completed > 0 && result.rafLatencyMs.n === 0) {
    return true;
  }
  return false;
}

const AGENT_COUNT = Number(process.argv[2] ?? "3");
const HISTORY_COUNT = Number(process.argv[3] ?? "1000");
const KEYSTROKES = Number(process.argv[4] ?? "30");
const TICK_MS = Number(process.argv[5] ?? "200");
const ERROR_AGENTS = process.argv[6] ?? "none"; // "all" | "none"
// Optional 7th arg (e.g. "run1"): repeated runs of the SAME scenario would
// otherwise silently overwrite the same JSON/trace filename, leaving only
// the LAST run's evidence on disk even after multiple invocations -- an
// earlier round of this same bench made exactly that mistake. Empty by
// default so single-run usage (the common case) is unaffected.
const RUN_LABEL = process.argv[7] ?? "";
// Unlike the other args (numeric, or "all"/"none"), this one flows straight
// into path.join() for the output filenames with no other validation --
// a value containing "/" or ".." would write outside results/candidateA.
if (RUN_LABEL !== "" && !/^[A-Za-z0-9_-]+$/.test(RUN_LABEL)) {
  console.error(
    `runLabel must match /^[A-Za-z0-9_-]+$/, got: ${JSON.stringify(RUN_LABEL)}`,
  );
  process.exit(1);
}

const outDir = path.join(__dirname, "results", "candidateA");
fs.mkdirSync(outDir, { recursive: true });

writeBeforeSnapshot();
try {
  await withServer(async (baseUrl) => {
    const browser = await chromium.launch();
    const results = {};
    for (const variant of ["before", "after"]) {
      const page = await browser.newPage();
      // Candidate A's whole point is that this CAN get slow at scale --
      // Playwright's 30s default action timeout would abort a genuinely
      // slow "after" run as a script error rather than a measurement.
      page.setDefaultTimeout(120000);
      try {
        const raw = await measure(page, baseUrl, variant, {
          agentCount: AGENT_COUNT,
          historyCount: HISTORY_COUNT,
          keystrokes: KEYSTROKES,
          tickMs: TICK_MS,
          errorAgents: ERROR_AGENTS,
          traceDir: outDir,
          runLabel: RUN_LABEL,
        });
        results[variant] = summarize(raw);
        console.log(variant, JSON.stringify(results[variant], null, 2));
      } catch (err) {
        results[variant] = { error: String(err?.message ?? err) };
        console.log(variant, "FAILED:", results[variant].error);
      }
      await page.close();
    }
    await browser.close();

    const outFile = path.join(
      outDir,
      `candidateA-agents${AGENT_COUNT}-hist${HISTORY_COUNT}-tick${TICK_MS}-err${ERROR_AGENTS}${RUN_LABEL ? `-${RUN_LABEL}` : ""}.json`,
    );
    fs.writeFileSync(
      outFile,
      JSON.stringify(
        {
          agentCount: AGENT_COUNT,
          historyCount: HISTORY_COUNT,
          keystrokes: KEYSTROKES,
          tickMs: TICK_MS,
          errorAgents: ERROR_AGENTS,
          runLabel: RUN_LABEL || undefined,
          ...results,
        },
        null,
        2,
      ),
    );
    console.log("written", outFile);

    if (Object.values(results).some(scenarioFailed)) {
      console.error(
        "FAIL: at least one variant did not produce a valid measurement " +
          "(harness error / slash-menu did not appear / typing did not " +
          "finish / a required field is missing) -- see the JSON above " +
          "for which one and why.",
      );
      process.exitCode = 1;
    }
  });
} finally {
  removeBeforeSnapshot();
}
