// issue #304 M2/M3: App-level input-latency bench. Mounts the REAL
// src/App.svelte (see bench/harnessApp.ts) against bench/fakePhoenix.ts and
// drives it with Playwright, comparing "before" (1c399eae^, the commit
// immediately before candidate A -- App.svelte's latestErrorKeyByAgent
// full-transcript rescan on every `logs` replacement) against "after" (the
// current worktree). Adds Event Timing (input delay / processing /
// presentation), long tasks, DOM node count, and a Playwright trace on top
// of the #174-era rAF-only metric (kept for comparability).
//
//   PATH="$HOME/.asdf/shims:$PATH" node bench/runBenchApp.mjs \
//     [agentCount] [historyCount] [keystrokes] [tickMs] [errorAgents]
//
// agentCount:   total agents seeded (1 viewed + agentCount-1 background)
// historyCount: synthetic transcript length per agent
// keystrokes:   composer keystrokes typed (plain "a", one per ~30ms cycle)
// tickMs:       interval between live-log receive ticks, sent to the
//               viewed agent AND one background agent at this SAME
//               frequency each tick (candidate A's own reproduction recipe)
// errorAgents:  "all" | "none" -- whether every seeded agent's history ends
//               with an is_error result (candidate A: "error あり/なし")
import { chromium } from "@playwright/test";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

// The commit immediately before candidate A (issue #287 fuji2 round-1 M1)
// replaced a plain `$state` sticky-badge write (set once per matching live
// envelope) with `latestErrorKeyByAgent`, a `$derived.by` that rescans
// EVERY agent's WHOLE transcript backwards on every `logs` replacement.
// App.svelte is the only file this isolates -- latestReply.ts also changed
// in 1c399eae but for an unrelated error-text fallback, not this path.
const BASELINE_SHA = "1c399eae1c278bfa4892019350dc1ad4ccd7afde^";
const BEFORE_SNAPSHOT_PATH = path.join(root, "src/.App.before.bench.svelte");

function writeBeforeSnapshot() {
  const content = execFileSync(
    "git",
    ["show", `${BASELINE_SHA}:dashboard/src/App.svelte`],
    { cwd: root, encoding: "utf8" },
  );
  const header = `<!--\n  issue #304 bench fixture -- generated by runBenchApp.mjs from baseline\n  ${BASELINE_SHA} (git show <SHA>:dashboard/src/App.svelte), the commit\n  immediately before candidate A (issue #287 fuji2 M1). Temporary: deleted\n  when the bench run finishes. Do not edit or commit (gitignored).\n-->\n`;
  fs.writeFileSync(BEFORE_SNAPSHOT_PATH, header + content);
}

function removeBeforeSnapshot() {
  fs.rmSync(BEFORE_SNAPSHOT_PATH, { force: true });
}

async function withServer(fn) {
  const server = await createServer({
    root,
    configFile: path.join(__dirname, "vite.harness.config.ts"),
    server: { port: 0 },
    logLevel: "error",
  });
  await server.listen();
  const address = server.httpServer?.address();
  const port = typeof address === "object" && address ? address.port : address;
  try {
    return await fn(`http://localhost:${port}`);
  } finally {
    await server.close();
  }
}

function armProbes(page) {
  return page.evaluate(() => {
    window.__bench.armLatencyProbe();
    window.__eventTimings = [];
    // `buffered: true` deliberately OMITTED here: it would replay entries
    // from before this point (mount, seed, click-into-detail), inflating
    // these stats with one-time setup cost instead of isolating the
    // during-typing/during-receive-tick window this function arms for.
    new PerformanceObserver((list) => {
      for (const e of list.getEntries()) {
        window.__eventTimings.push({
          name: e.name,
          startTime: e.startTime,
          duration: e.duration,
          inputDelay: e.processingStart - e.startTime,
          processingTime: e.processingEnd - e.processingStart,
          presentationDelay: e.duration - (e.processingEnd - e.startTime),
        });
      }
    }).observe({ type: "event", durationThreshold: 16 });
    window.__longTasks = [];
    new PerformanceObserver((list) => {
      for (const e of list.getEntries()) {
        window.__longTasks.push({
          name: e.name,
          startTime: e.startTime,
          duration: e.duration,
          attribution: (e.attribution ?? []).map((a) => ({
            name: a.name,
            containerType: a.containerType,
          })),
        });
      }
    }).observe({ type: "longtask" });
  });
}

/** Same instruments as armProbes, but buffered from navigation -- used
 *  once right after mount to report one-time mount cost SEPARATELY from
 *  the during-typing/during-receive-tick window (not mixed into it). */
function mountCostSoFar(page) {
  return page.evaluate(() => ({
    longTasks: performance
      .getEntriesByType("longtask")
      .map((e) => ({ name: e.name, startTime: e.startTime, duration: e.duration })),
  }));
}

async function measure(page, baseUrl, variant, opts) {
  const { agentCount, historyCount, keystrokes, tickMs, errorAgents, traceDir } = opts;
  await page.goto(
    `${baseUrl}/bench/harnessApp.html?variant=${variant}&token=bench-${variant}`,
    { waitUntil: "load" },
  );
  await page.evaluate(() => window.__bench.waitReady());

  const agents = Array.from({ length: agentCount }, (_, i) => ({
    agentId: i === 0 ? "agent-viewed" : `agent-bg-${i}`,
    historyCount,
    withRecentError: errorAgents === "all",
    ext:
      i === 0
        ? { slash_commands: ["new", "clear", "help"] }
        : undefined,
  }));
  await page.evaluate((a) => window.__bench.seed(a), agents);
  // Let the initial mount + snapshot/history render settle before opening
  // the detail view or measuring, mirroring bench/harness.ts's 1500ms
  // settle window.
  await page.waitForTimeout(1500);

  await page
    .locator("button.open", { hasText: "agent-viewed" })
    .click();
  await page.waitForSelector(".log", { timeout: 30000 });
  await page.waitForTimeout(500);

  const mountCost = await mountCostSoFar(page);
  await armProbes(page);

  const domCountBefore = await page.evaluate(
    () => document.querySelectorAll("*").length,
  );

  await page.context().tracing.start({ screenshots: false, snapshots: false });

  // Receive-tick generator: same frequency to the viewed agent and one
  // background agent every tick, running concurrently with the composer
  // keystrokes below (candidate A's own reproduction recipe: "閲覧agentと
  // 背景agentへの同頻度送信"). try/finally: candidate A's whole failure
  // mode is the page becoming unresponsive long enough for `textarea.type`
  // to time out below -- without this, the leaked interval keeps firing
  // page.evaluate() against an already-closed page after the catch in the
  // caller closes it, crashing the whole script instead of just failing
  // this one variant's measurement.
  let seqCounter = historyCount + 1;
  let tickHandle;
  if (agentCount > 1 && tickMs > 0) {
    tickHandle = setInterval(() => {
      const seq = seqCounter++;
      page
        .evaluate(
          ({ seq }) => {
            window.__bench.sendLog("agent-viewed", seq);
            window.__bench.sendLog("agent-bg-1", seq);
          },
          { seq },
        )
        .catch(() => {
          // Page busy/closed -- expected under the exact contention this
          // scenario is trying to provoke; the next tick (or the outer
          // clearInterval) is the recovery, not this call.
        });
    }, tickMs);
  }

  let typingError = null;
  let keystrokesCompleted = 0;
  try {
    const textarea = page.locator("textarea").first();
    await textarea.click();
    for (let i = 0; i < keystrokes; i++) {
      await textarea.type("a", { delay: 0 });
      keystrokesCompleted++;
      await page.waitForTimeout(30);
    }
  } catch (err) {
    // Candidate A's own failure mode -- a hung main thread that starves
    // even a single keystroke past this run's timeout. Keep the partial
    // trace/samples gathered up to this point rather than losing the
    // whole measurement to the exception.
    typingError = String(err?.message ?? err);
  } finally {
    if (tickHandle) clearInterval(tickHandle);
  }
  await page.waitForTimeout(200).catch(() => {});

  const tracePath = path.join(
    traceDir,
    `trace-agents${agentCount}-hist${historyCount}-tick${tickMs}-err${errorAgents}-${variant}.zip`,
  );
  await page.context().tracing.stop({ path: tracePath }).catch(() => {});

  const domCountAfter = await page
    .evaluate(() => document.querySelectorAll("*").length)
    .catch(() => null);
  const latencies = await page.evaluate(() => window.__latencies).catch(() => []);
  const eventTimings = await page
    .evaluate(() => window.__eventTimings)
    .catch(() => []);
  const longTasks = await page.evaluate(() => window.__longTasks).catch(() => []);

  return {
    latencies,
    eventTimings,
    longTasks,
    mountLongTasks: mountCost.longTasks,
    domCountBefore,
    domCountAfter,
    tracePath,
    typingError,
    keystrokesCompleted,
    keystrokesRequested: keystrokes,
  };
}

function stats(values) {
  if (values.length === 0) return { n: 0 };
  const sorted = [...values].sort((a, b) => a - b);
  const sum = sorted.reduce((a, b) => a + b, 0);
  const pct = (p) =>
    sorted[Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))];
  return {
    n: sorted.length,
    avg: Number((sum / sorted.length).toFixed(2)),
    median: Number(pct(50).toFixed(2)),
    p95: Number(pct(95).toFixed(2)),
    max: Number(pct(100).toFixed(2)),
  };
}

function summarize(raw) {
  return {
    rafLatencyMs: stats(raw.latencies),
    eventTiming: {
      inputDelayMs: stats(raw.eventTimings.map((e) => e.inputDelay)),
      processingTimeMs: stats(raw.eventTimings.map((e) => e.processingTime)),
      presentationDelayMs: stats(raw.eventTimings.map((e) => e.presentationDelay)),
      durationMs: stats(raw.eventTimings.map((e) => e.duration)),
    },
    longTasks: {
      count: raw.longTasks.length,
      totalDurationMs: Number(
        raw.longTasks.reduce((a, t) => a + t.duration, 0).toFixed(2),
      ),
      durationMs: stats(raw.longTasks.map((t) => t.duration)),
    },
    mountLongTasks: {
      count: raw.mountLongTasks.length,
      totalDurationMs: Number(
        raw.mountLongTasks.reduce((a, t) => a + t.duration, 0).toFixed(2),
      ),
    },
    domNodeCount: { before: raw.domCountBefore, after: raw.domCountAfter },
    tracePath: raw.tracePath,
    typingError: raw.typingError,
    keystrokes: { completed: raw.keystrokesCompleted, requested: raw.keystrokesRequested },
  };
}

const AGENT_COUNT = Number(process.argv[2] ?? "3");
const HISTORY_COUNT = Number(process.argv[3] ?? "1000");
const KEYSTROKES = Number(process.argv[4] ?? "30");
const TICK_MS = Number(process.argv[5] ?? "200");
const ERROR_AGENTS = process.argv[6] ?? "none"; // "all" | "none"

const outDir = path.join(__dirname, "results", "candidateA");
fs.mkdirSync(outDir, { recursive: true });

writeBeforeSnapshot();
try {
  await withServer(async (baseUrl) => {
    const browser = await chromium.launch();
    const results = {};
    for (const variant of ["before", "after"]) {
      const page = await browser.newPage();
      // Candidate A's whole point is that this CAN get slow at scale --
      // Playwright's 30s default action timeout would abort a genuinely
      // slow "after" run as a script error rather than a measurement.
      page.setDefaultTimeout(120000);
      try {
        const raw = await measure(page, baseUrl, variant, {
          agentCount: AGENT_COUNT,
          historyCount: HISTORY_COUNT,
          keystrokes: KEYSTROKES,
          tickMs: TICK_MS,
          errorAgents: ERROR_AGENTS,
          traceDir: outDir,
        });
        results[variant] = summarize(raw);
        console.log(variant, JSON.stringify(results[variant], null, 2));
      } catch (err) {
        results[variant] = { error: String(err?.message ?? err) };
        console.log(variant, "FAILED:", results[variant].error);
      }
      await page.close();
    }
    await browser.close();

    const outFile = path.join(
      outDir,
      `candidateA-agents${AGENT_COUNT}-hist${HISTORY_COUNT}-tick${TICK_MS}-err${ERROR_AGENTS}.json`,
    );
    fs.writeFileSync(
      outFile,
      JSON.stringify(
        {
          agentCount: AGENT_COUNT,
          historyCount: HISTORY_COUNT,
          keystrokes: KEYSTROKES,
          tickMs: TICK_MS,
          errorAgents: ERROR_AGENTS,
          ...results,
        },
        null,
        2,
      ),
    );
    console.log("written", outFile);
  });
} finally {
  removeBeforeSnapshot();
}
