#!/usr/bin/env bash
# Build a self-contained runner tarball (issue #70, ADR-0018).
#
# The output needs nothing but a Node runtime on the target host: the wrapper
# packages, their engine CLIs (Claude Code / codex ship as platform-specific
# npm packages) and every native module are inside. Setting it up is
# "unpack -> edit config -> run", with no pnpm install / build / workspace
# resolution on the deployment host.
#
#   scripts/build-runner-tarball.sh [--target <os>-<arch>] [--out <dir>]
#
#   --target  darwin-arm64 | linux-x64   (default: this host)
#   --out     output directory (default: <repo>/dist-tarball). A RELATIVE path
#             is resolved against the repository root, not the caller's cwd,
#             because the script cds to the root first.
#
# Cross-building works because pnpm can fetch another platform's optional
# dependencies (`supportedArchitectures`), which this script injects into
# pnpm-workspace.yaml for the duration of the build and then reverts. A
# darwin host can therefore produce the linux-x64 archive.
#
# NOT SAFE TO RUN CONCURRENTLY. That injection mutates a tracked file in the
# working tree, so two builds would race on it (and on the staging dir), and a
# lost revert would leave the tree dirty. A lock dir enforces one build at a
# time — build the two targets sequentially.
#
# Three pnpm quirks are handled here so callers never see them:
#   1. `pnpm deploy` needs `--legacy` unless the workspace sets
#      inject-workspace-packages=true.
#   2. Its output path is resolved relative to the workspace, so an absolute
#      target silently breaks (it tried to mkdir /Users/tmp for /tmp/x).
#   3. It honours .gitignore for the deployed package itself — runner's
#      `files` list in package.json is what keeps dist/ in the archive.
set -euo pipefail

root=$(cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"

host_os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$(uname -m)" in
  arm64 | aarch64) host_cpu=arm64 ;;
  x86_64 | amd64) host_cpu=x64 ;;
  *) host_cpu=$(uname -m) ;;
esac

target="$host_os-$host_cpu"
out="$root/dist-tarball"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      target="${2:?--target needs a value}"
      shift 2
      ;;
    --out)
      out="${2:?--out needs a value}"
      shift 2
      ;;
    -h | --help)
      # Print the header block, whatever its length: everything between the
      # shebang and `set -`.
      awk 'NR > 1 && /^set -/ { exit } NR > 1' "$0"
      exit 0
      ;;
    *)
      echo "build-runner-tarball: unknown option: $1" >&2
      exit 64 # EX_USAGE
      ;;
  esac
done

# Only the two officially distributed targets (ADR-0018 改訂). A host outside
# them (Intel mac, arm64 Linux) must pass --target explicitly; widen this list
# together with that decision, not ahead of it.
case "$target" in
  darwin-arm64 | linux-x64) ;;
  *)
    echo "build-runner-tarball: unsupported target: $target" >&2
    echo "  expected darwin-arm64 | linux-x64" >&2
    exit 64
    ;;
esac
target_os=${target%-*}
target_cpu=${target##*-}

for cmd in pnpm node tar; do
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "build-runner-tarball: $cmd not found in PATH" >&2
    exit 69 # EX_UNAVAILABLE
  }
done

# Serialise builds. mkdir is atomic, so it doubles as the lock; taking it
# BEFORE touching the working tree is what keeps two runs from racing on the
# pnpm-workspace.yaml injection.
lock="$root/.tarball-build.lock"
if ! mkdir "$lock" 2>/dev/null; then
  echo "build-runner-tarball: another build holds $lock" >&2
  echo "  builds mutate pnpm-workspace.yaml and cannot run in parallel —" >&2
  echo "  run the targets sequentially, or remove a stale lock dir." >&2
  exit 75 # EX_TEMPFAIL
fi

# Staging dir must be workspace-relative (quirk 2 above). The pid keeps the
# leftovers of a SIGKILLed run from colliding with a later build.
stage_rel=".tarball-build.$$"
stage="$root/$stage_rel"
ws="$root/pnpm-workspace.yaml"
ws_backup="$stage/pnpm-workspace.yaml.orig"

cleanup() {
  if [[ -f "$ws_backup" ]]; then
    cp "$ws_backup" "$ws"
  fi
  rm -rf "$stage"
  rmdir "$lock" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

rm -rf "$stage"
mkdir -p "$stage" "$out"

echo "build-runner-tarball: target=$target"

echo "build-runner-tarball: building TypeScript"
pnpm -C wrapper build >/dev/null
pnpm -C runner build >/dev/null

# issue #228: read the SAME build-info.json cli.ts itself reads at runtime
# (generated by runner/scripts/generate-build-info.mjs as the last step of
# `pnpm -C runner build` above) instead of a second, independent
# `git rev-parse` / dirty check here — two separate computations could
# disagree (e.g. a different dirty definition), silently making this
# archive's own VERSION file lie about what actually shipped in dist/.
# Single source of truth for both revision AND the dirty definition
# (director's steer, issue #228 query round 2). The `<rev>[-dirty]` string
# itself is formatted by the SAME scripts/build-identity.mjs `--format`
# call the server build script's docs point at, so this VERSION file and
# runner's own formatBuildRevision() cannot silently drift into two
# different formats either (issue #228 round 2 MF-5, ふじ 差し戻し).
build_info="$root/runner/dist/build-info.json"
[[ -f "$build_info" ]] || {
  echo "build-runner-tarball: $build_info missing after build" >&2
  exit 70 # EX_SOFTWARE
}
version_string=$(node "$root/scripts/build-identity.mjs" --format "$build_info")
name="kaoiro-runner-$version_string-$target"
echo "build-runner-tarball: rev=$version_string"

# Cross-target: ask pnpm for the other platform's optional dependencies. Note
# the archive then also carries that platform's musl variants — a `libc`
# filter does not exclude them — which is why the linux archive works on both
# glibc and musl hosts (at the cost of ~300 MB).
if [[ "$target" != "$host_os-$host_cpu" ]]; then
  echo "build-runner-tarball: fetching $target optional dependencies"
  cp "$ws" "$ws_backup"
  cat >>"$ws" <<YAML

# Injected by scripts/build-runner-tarball.sh (reverted after the build).
supportedArchitectures:
  os:
    - $target_os
  cpu:
    - $target_cpu
YAML
fi

echo "build-runner-tarball: pnpm deploy"
pnpm --filter=@kaoiro/runner --prod deploy "$stage_rel/$name" --legacy >/dev/null

# The launch shim resolves ../dist/cli.js from its own directory, so the deploy
# tree needs no rearranging: deploy/ and dist/ are already siblings.
[[ -f "$stage/$name/dist/cli.js" ]] || {
  echo "build-runner-tarball: dist/cli.js missing from the deploy tree" >&2
  exit 70 # EX_SOFTWARE
}
[[ -x "$stage/$name/deploy/kaoiro-runner-launch.sh" ]] || {
  echo "build-runner-tarball: launch shim missing or not executable" >&2
  exit 70
}
printf '%s\n' "$version_string" >"$stage/$name/VERSION"

echo "build-runner-tarball: archiving"
# COPYFILE_DISABLE=1 stops macOS bsdtar from embedding its copyfile
# metadata (resource forks / ACLs) as AppleDouble `._*` files, which a
# GNU tar extraction on the Linux deploy target otherwise unpacks as
# bogus top-level entries (issue #153, found in #148's real-host
# verification). A no-op on Linux, where GNU tar ignores the var.
COPYFILE_DISABLE=1 tar czf "$out/$name.tar.gz" -C "$stage" "$name"

echo "build-runner-tarball: done"
du -h "$out/$name.tar.gz"
