// Interactive setup wizard for the runner (issue #144, spec setup-wizards).
// Writes runner.config.json and runner.env into the OS user config dir, so a
// freshly unpacked distribution archive (issue #70) needs no hand-editing.
//
// The prompting surface is injected (`Prompt`) so the flow is unit-testable
// without a TTY; `setup-cli.ts` wires the readline implementation.

import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join } from "node:path";
import { type RunnerConfig, parseRunnerConfig } from "./config.js";

/** 32-byte hex — the spec's `openssl rand -hex 32` without the openssl
 *  dependency (the archive cannot assume it on the deployment host). */
export function generateToken(): string {
  return randomBytes(32).toString("hex");
}

/**
 * Per-OS user config dir. MUST stay in sync with
 * `deploy/kaoiro-runner-launch.sh`, which resolves the same paths at start —
 * a divergence would make the wizard write where the service never looks.
 * KAOIRO_RUNNER_DIR overrides both.
 */
export function resolveConfigDir(
  env: Record<string, string | undefined>,
  platform: string,
  home: string,
): string {
  const override = env.KAOIRO_RUNNER_DIR;
  if (override !== undefined && override !== "") return override;
  if (platform === "darwin") {
    return join(home, "Library", "Application Support", "kaoiro");
  }
  const xdg = env.XDG_CONFIG_HOME;
  const base = xdg !== undefined && xdg !== "" ? xdg : join(home, ".config");
  return join(base, "kaoiro");
}

export interface SetupAnswers {
  hostId: string;
  serverUrl: string;
  cwdAllowlist: string[];
  capabilities: string[];
  /** Empty string = leave the token unset (dev mode: server-side runner auth
   *  disabled). Written to runner.env, never to the JSON config. */
  token: string;
  /** Absolute path to node, for hosts where a version manager owns it. */
  nodePath?: string;
  /** Only meaningful when capabilities include codex. Explicit values keep the
   *  runner from shelling out to `codex doctor` (phase-24). The literals must
   *  match `CodexConfig["auth_mode"]` in config.ts — `parseRunnerConfig`
   *  rejects anything else. */
  codexAuthMode?: "chatgpt" | "apikey";
}

/** Builds the config and validates it through the runtime loader, so the
 *  wizard can never emit a file the runner would reject on start. */
export function buildRunnerConfig(answers: SetupAnswers): RunnerConfig {
  const raw: Record<string, unknown> = {
    host_id: answers.hostId,
    server_url: answers.serverUrl,
    cwd_allowlist: answers.cwdAllowlist,
    capabilities: answers.capabilities,
  };
  if (answers.capabilities.includes("codex") && answers.codexAuthMode) {
    raw.codex = { auth_mode: answers.codexAuthMode };
  }
  return parseRunnerConfig(raw);
}

/** The env file is SOURCED by the launch shim, so every line must be valid
 *  shell. Values are single-quoted (with `'` escaped) because a token is
 *  opaque and a node path may contain spaces. */
export function buildRunnerEnv(answers: SetupAnswers): string {
  const quote = (value: string): string =>
    `'${value.replaceAll("'", "'\\''")}'`;
  const lines = [
    "# Generated by the kaoiro runner setup wizard (issue #144).",
    "# Sourced by deploy/kaoiro-runner-launch.sh at service start. Keep the",
    "# file mode at 0600 — it holds the runner auth token.",
    "",
  ];
  if (answers.token === "") {
    lines.push(
      "# Server-side runner auth is disabled while this is unset (dev only;",
      "# a prod server rejects the connection fail-closed, issue #138).",
      "#KAOIRO_RUNNER_TOKEN=",
    );
  } else {
    lines.push(`KAOIRO_RUNNER_TOKEN=${quote(answers.token)}`);
  }
  lines.push("");
  if (answers.nodePath !== undefined && answers.nodePath !== "") {
    lines.push(
      "# Pinned because systemd user units / launchd agents start with a",
      "# minimal PATH.",
      `KAOIRO_NODE=${quote(answers.nodePath)}`,
    );
  } else {
    lines.push(
      "# Pin this when a version manager (nvm / fnm / asdf) owns node:",
      "#KAOIRO_NODE=/home/you/.nvm/versions/node/v22.20.0/bin/node",
    );
  }
  return `${lines.join("\n")}\n`;
}

/** Minimal prompting surface, injected so the flow can be driven by tests. */
export interface Prompt {
  ask(question: string, fallback?: string): Promise<string>;
  confirm(question: string, fallback: boolean): Promise<boolean>;
  info(message: string): void;
}

export interface SetupResult {
  configPath: string;
  envPath: string;
  /** Paths the operator declined to overwrite. */
  skipped: string[];
  /** The chosen token, or "" when none was set. Returned so the caller can
   *  print the server-side `KAOIRO_RUNNER_TOKENS` pairing line. */
  token: string;
}

const CAPABILITY_CHOICES = ["claude-code", "codex"] as const;

async function askHostId(prompt: Prompt, fallback: string): Promise<string> {
  for (;;) {
    const value = (await prompt.ask("Host ID", fallback)).trim();
    if (/^[A-Za-z0-9._-]+$/.test(value)) return value;
    prompt.info("  host ID may only contain letters, digits, '.', '_', '-'");
  }
}

async function askServerUrl(prompt: Prompt, fallback: string): Promise<string> {
  for (;;) {
    const value = (await prompt.ask("Server runner URL", fallback)).trim();
    if (value.startsWith("ws://") || value.startsWith("wss://")) return value;
    prompt.info("  must start with ws:// or wss://");
    prompt.info(
      "  note: a prod server behind TLS needs wss:// — force_ssl rejects" +
        " plain ws:// with a 301",
    );
  }
}

/** At least one absolute path; blank input ends the list. */
async function askCwdAllowlist(prompt: Prompt): Promise<string[]> {
  const paths: string[] = [];
  prompt.info(
    "Directories agents may be launched in (absolute paths, blank to end):",
  );
  for (;;) {
    const value = (await prompt.ask(`  path #${paths.length + 1}`)).trim();
    if (value === "") {
      if (paths.length > 0) return paths;
      prompt.info("  at least one directory is required");
      continue;
    }
    if (!isAbsolute(value)) {
      prompt.info("  must be an absolute path");
      continue;
    }
    paths.push(value);
  }
}

async function askCapabilities(prompt: Prompt): Promise<string[]> {
  const chosen: string[] = [];
  for (const capability of CAPABILITY_CHOICES) {
    if (await prompt.confirm(`Enable engine '${capability}'?`, true)) {
      chosen.push(capability);
    }
  }
  if (chosen.length === 0) {
    prompt.info("  no engine selected; enabling claude-code");
    return ["claude-code"];
  }
  return chosen;
}

/** Writes `content` unless the file exists and the operator declines. */
async function writeGuarded(
  prompt: Prompt,
  path: string,
  content: string,
  mode: number,
  skipped: string[],
): Promise<void> {
  if (existsSync(path)) {
    if (!(await prompt.confirm(`${path} exists — overwrite?`, false))) {
      skipped.push(path);
      return;
    }
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, { mode });
  // `mode` on writeFileSync only applies when the file is CREATED — POSIX
  // open(2) ignores it for an existing path. Overwriting a runner.env that was
  // previously created 0644 would otherwise leave the token world-readable, so
  // enforce the mode unconditionally.
  chmodSync(path, mode);
}

/**
 * Runs the whole wizard: asks, then writes runner.config.json (0644) and
 * runner.env (0600). Returns where things landed so the caller can print the
 * follow-up steps.
 */
export async function runSetup(
  prompt: Prompt,
  options: {
    env: Record<string, string | undefined>;
    platform: string;
    home?: string;
  },
): Promise<SetupResult> {
  const home = options.home ?? homedir();
  const dir = resolveConfigDir(options.env, options.platform, home);
  const configPath = join(dir, "runner.config.json");
  const envPath = join(dir, "runner.env");

  prompt.info(`Writing configuration to ${dir}`);
  prompt.info("");

  const hostId = await askHostId(prompt, "");
  const serverUrl = await askServerUrl(prompt, "ws://localhost:4000/runner");
  const cwdAllowlist = await askCwdAllowlist(prompt);
  const capabilities = await askCapabilities(prompt);

  let codexAuthMode: SetupAnswers["codexAuthMode"];
  if (capabilities.includes("codex")) {
    codexAuthMode = (await prompt.confirm(
      "Codex signs in with a ChatGPT plan (no = API key)?",
      true,
    ))
      ? "chatgpt"
      : "apikey";
  }

  // The token pairs with the server's KAOIRO_RUNNER_TOKENS entry
  // `<host_id>:<token>`; the wizards do not exchange it for you (spec:
  // independent operation), so it is echoed once for copying.
  let token = "";
  if (await prompt.confirm("Set a runner auth token?", true)) {
    if (await prompt.confirm("  generate one automatically?", true)) {
      token = generateToken();
      prompt.info(`  generated: ${token}`);
    } else {
      token = (await prompt.ask("  token")).trim();
    }
  }

  const nodePath = (
    await prompt.ask("Absolute path to node (blank = use PATH)", "")
  ).trim();

  const answers: SetupAnswers = {
    hostId,
    serverUrl,
    cwdAllowlist,
    capabilities,
    token,
    ...(nodePath === "" ? {} : { nodePath }),
    ...(codexAuthMode === undefined ? {} : { codexAuthMode }),
  };

  const config = buildRunnerConfig(answers);
  const skipped: string[] = [];
  await writeGuarded(
    prompt,
    configPath,
    `${JSON.stringify(config, null, 2)}\n`,
    0o644,
    skipped,
  );
  await writeGuarded(
    prompt,
    envPath,
    buildRunnerEnv(answers),
    0o600,
    skipped,
  );

  return { configPath, envPath, skipped, token };
}

/** Follow-up steps. Deliberately terse: the deployment runbook (issue #142)
 *  is the manual source of truth, this only says what to do next. */
export function nextSteps(result: SetupResult, token: string): string[] {
  const steps = [
    `config: ${result.configPath}`,
    `env:    ${result.envPath} (mode 0600)`,
    "",
  ];
  if (result.skipped.length > 0) {
    steps.push(`kept existing: ${result.skipped.join(", ")}`, "");
  }
  if (token !== "") {
    steps.push(
      "1. On the server, add this host to KAOIRO_RUNNER_TOKENS in .env:",
      `     KAOIRO_RUNNER_TOKENS=<host_id>:${token}`,
      "   (`mix kaoiro.env` on the server can generate that file)",
    );
  } else {
    steps.push(
      "1. No token was set — the server must run with runner auth disabled",
      "   (dev only; a prod server rejects the connection).",
    );
  }
  steps.push(
    "2. Start it: deploy/kaoiro-runner-launch.sh",
    "3. To run it as a service, install the systemd unit / launchd agent",
    "   from deploy/ — see runner/README.md「常駐化」.",
  );
  return steps;
}
